FROM node:20-alpine

# Accept build-time database URL
ARG DATABASE_URL
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN pnpm install

# Copy rest of the code
COPY . .

# Generate prisma client
RUN pnpm run generate:db

# Run turbo build filtered for frontend (Next.js app)
RUN DATABASE_URL=$DATABASE_URL pnpm exec turbo build --filter=web...

EXPOSE 3000

CMD ["pnpm", "start:frontend"]