FROM node:20-alpine

WORKDIR /usr/src/app

# Install pnpm globally
RUN npm install -g pnpm

# Copy entire monorepo first (important!)
COPY . .

# Install dependencies
RUN pnpm install

# Accept DB URL and set it for prisma
ARG DB_URL
ENV DATABASE_URL=$DB_URL

# Generate Prisma client (inside packages/prisma)
RUN pnpm run generate:db

# Build the backend (TypeScript → dist)
RUN pnpm run build:backend

EXPOSE 3002

CMD ["pnpm", "start:backend"]
