## Build the docker code
## Push the docker image to Dockerhub
## SSH into the our VM and start the new image

name: Continuous Deployment (Prod) (Backend)
on:
    push:
        branches: [ main ] 
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v2

            - name: Login to docker hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and Push
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./docker/Dockerfile.backend
                push: true
                tags: saksham251/todo-app-backend:${{github.sha}}
                build-args: |
                  DB_URL=${{ secrets.DATABASE_URL }}
            - run: |
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > saksham_aws.pem
                chmod 600 saksham_aws.pem
                ssh -i saksham_aws.pem -o StrictHostKeyChecking=no ubuntu@13.202.34.192 << 'EOF'
                echo "Stopping old container if running..."
                docker stop todo_backend || true
                docker rm todo_backend || true
                echo "Pulling new image..."
                docker pull saksham251/todo-app-backend:${{ github.sha }}
                echo "Starting new container..."
                docker run -d --name todo_backend -p 3002:3002 saksham251/todo-app-backend:${{ github.sha }}
                EOF
     